name: eduit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_core: ^2.4.1
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  flutter_custom_carousel_slider: ^1.0.0
  anim_search_bar: ^2.0.3
  persistent_bottom_nav_bar: ^5.0.2
  share_plus: 
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  http: ^0.13.5
  flutter_share: ^2.0.0
  dropdown_button2: ^2.1.3
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter
  
  
flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserratt.ttf



